services:
  - type: web
    name: rancho-comanche-api
    runtime: docker
    dockerfilePath: backend/projeto-rancho/Dockerfile
    dockerContext: backend/projeto-rancho
    plan: free
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: H2_CONSOLE_ENABLED
        value: "false"
      - key: APP_FRONTEND_URL
        value: https://miguellima11.github.io/Rancho-Poc
